version: 2
jobs:
  build:
    working_directory: ~/app
    machine:
      image: circleci/classic:latest
      timezone: Europe/Zagreb
    steps:
      - checkout
      - run: cp .env.sample .env
      - restore_cache:
          keys:
            - v1-docker-{{ .Branch }}
      - run:
          name: Load Docker layers cache
          command: |
            set +o pipefail
            docker load -i ~/docker-layers.tar | true
      - run:
          name: Build application Docker image
          command: |
            export IMAGE_TAG=$CIRCLE_SHA1
            docker-compose -p ${CIRCLE_PROJECT_REPONAME} build
      - run:
          name: Tag docker image as latest
          command: |
            docker tag nodefactory/eatmybet:${CIRCLE_SHA1} nodefactory/eatmybet:latest
      - run:
          name: Run backend tests
          command: docker-compose run --no-deps --rm backend npm run test
      - run:
          name: Run contract tests
          command: |
            set -ex
            docker-compose run --rm backend truffle "test *"
      - run:
          name: Save docker layers cache
          command: |
            docker save -o ~/docker-layers.tar nodefactory/eatmybet:${CIRCLE_SHA1} trufflesuite/ganache-cli:v6.1.0 node:carbon-alpine
      - save_cache:
          key: v1-docker-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/docker-layers.tar
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./test-results
      - persist_to_workspace:
          root: ~/
          paths:
            - ./docker-layers.tar
  deploy-staging:
    working_directory: ~/app
    docker:
      - image: circleci/node:carbon
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker
      - checkout
      - run:
          name: Load Docker layers cache
          command: |
            set +o pipefail
            docker load -i ~/docker-layers.tar | true
      - run:
          name: Push image to Docker Hub
          command: |
            docker login --username="$DOCKER_HUB_USER" --password="$DOCKER_HUB_PASS"
            docker push nodefactory/eatmybet:${CIRCLE_SHA1}
            docker tag nodefactory/eatmybet:${CIRCLE_SHA1} nodefactory/eatmybet:latest
            docker push nodefactory/eatmybet:latest
      - run: "\
              ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
              deploy@nodefactory.io \
              \"env ENVIRONMENT=staging IMAGE_TAG=${CIRCLE_SHA1} DOCKER_USER=$DOCKER_HUB_USER DOCKER_PASSWORD=$DOCKER_HUB_PASS \
              /home/deploy/eatmybet/deploy.sh\" \
              "
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only:
                - master